#### general settings
name: train_u2net_x3_iphone
use_tb_logger: true
model: srgan
distortion: sr
scale: 1
gpu_ids: [0]

#### datasets
datasets:
  train:
    name: LQGTDeblur
    mode: LQGTDeblur
    aug: noise
    aug_count: 3
    noise_data: /home/web_server/zhouhuanxiang/disk/Real-SR-master/DPEDiphone_noise/
    dataroot_GT: /home/web_server/zhouhuanxiang/disk/data/HD_UGC_raw
    dataroot_LQ: /media/disk1/fordata/web_server/huangxiaozheng/blur_data

    use_shuffle: true
    n_workers: 2  # per GPU
    batch_size: 8
    GT_size: 256
    use_flip: true
    use_rot: true
    color: RGB

#### network structures
network_G:
  which_model_G: u2net_3
network_D:
  which_model_D: NLayerDiscriminator
  in_nc: 3
  nf: 64
  nlayer: 3

#### path
path:
  pretrain_model_G: ~
  pretrain_model_D: ~
  strict_load: true
#  resume_state: ~ #../experiments/training_states/model.state
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-4
  weight_decay_G: 0
  beta1_G: 0.9
  beta2_G: 0.999
  lr_D: !!float 1e-4
  weight_decay_D: 0
  beta1_D: 0.9
  beta2_D: 0.999
  lr_scheme: MultiStepLR

  niter: 200000
  warmup_iter: -1  # no warm up
  lr_steps: [40000, 80000, 120000, 160000]
  lr_gamma: 0.5

  pixel_criterion: l1
  pixel_weight: !!float 1e-2
  feature_criterion: l1
  feature_weight: 1
  gan_type: ragan  # gan | ragan
  gan_weight: !!float 5e-3

  D_update_ratio: 1
  D_init_iters: 0

  manual_seed: 10
  val_freq: 99999999

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3

# CUDA_VISIBLE_DEVICES=2 python ~/zhouhuanxiang/disk/Real-SR-master/codes/train.py -opt ~/zhouhuanxiang/disk/Real-SR-master/codes/options/kwai/train_kwai_u2net_2.yml
# CUDA_VISIBLE_DEVICES=2 nohup python ~/zhouhuanxiang/disk/Real-SR-master/codes/train.py -opt ~/zhouhuanxiang/disk/Real-SR-master/codes/options/kwai/train_kwai_u2net_2.yml &
