#### general settings
name: EDVR_Xiph42_woTSA_M
use_tb_logger: true
model: video_base
distortion: sr
scale: 1
gpu_ids: [6,7]

#### datasets
datasets:
  train:
    name: Xiph
    mode: Xiph
    interval_list: [1]
    random_reverse: false
    border_mode: false
    dataroot_GT: /home/web_server/zhouhuanxiang/disk/Xiph/Xiph
    dataroot_LQ: /home/web_server/zhouhuanxiang/disk/Xiph/Xiph_all_encoded_42
    metainfo_path: /home/web_server/zhouhuanxiang/mmsr/codes/data_scripts/y4m_metainfos_128.json
    cache_keys: ~

    N_frames: 5
    use_shuffle: true
    n_workers: 1  # per GPU
    batch_size: 32
    GT_size: 128
    LQ_size: 128
    use_flip: true
    use_rot: true
    color: RGB

#### network structures
network_G:
  which_model_G: EDVR
  nf: 64
  nframes: 5
  groups: 8
  front_RBs: 5
  back_RBs: 10
  predeblur: false
  HR_in: true
  w_TSA: false

#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 4e-4
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 120000
  warmup_iter: -1  # -1: no warm up
  T_period: [30000, 30000, 30000, 30000]
  restarts: [30000, 60000, 90000]
  restart_weights: [1, 1, 1]
  eta_min: !!float 1e-7

  pixel_criterion: cb
  pixel_weight: 1.0
  val_freq: !!float 5e3

  manual_seed: 0

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3

# python ~/zhouhuanxiang/mmsr/codes/train.py -opt ~/zhouhuanxiang/mmsr/codes/options/train/train_EDVR_Xiph42_woTSA_M.yml
