# Not exactly the same as SRGAN in <Photo-Realistic Single Image Super-Resolution Using a Generative Adversarial Network>
# With 16 Residual blocks w/o BN

#### general settings
name: SRResNet_KWAI40_slim0
use_tb_logger: true
model: sr
distortion: sr
scale: 1
gpu_ids: [0]

#### datasets
datasets:
  train:
    name: KWAI
    mode: LQGT
    dataroot_GT: /home/web_server/zhouhuanxiang/disk/data/HD_UGC_raw
    # dataroot_LQ: /home/web_server/zhouhuanxiang/disk/log_prev/log_20190905/EDSR_crf40_baseline/results-KWAIVIDEO-crf40
    dataroot_LQ: /home/web_server/zhouhuanxiang/disk/data/HD_UGC_crf40_raw

    use_shuffle: true
    n_workers: 1  # per GPU
    batch_size: 16
    GT_size: 128
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: KWAI-test
    mode: LQGT
    dataroot_GT: /home/web_server/zhouhuanxiang/disk/data/HD_UGC_raw_test
    dataroot_LQ: /home/web_server/zhouhuanxiang/disk/data/HD_UGC_crf40_raw_test

#### network structures
network_G:
  which_model_G: MSRResNet
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 12
  upscale: 1

#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~ 

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 2e-4
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 100000
  warmup_iter: -1  # no warm up
  T_period: [25000, 25000, 25000, 25000]
  restarts: [25000, 50000, 75000]
  restart_weights: [1, 1, 1]
  eta_min: !!float 1e-7

  pixel_criterion: l1
  pixel_weight: 1.0

  manual_seed: 10
  val_freq: !!float 5e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3


# python ~/zhouhuanxiang/mmsr/codes/train.py -opt ~/zhouhuanxiang/mmsr/codes/options/train/train_SRResNet_KWAI40_slim0.yml